### ISSUE TITLE
Tree datalist isEdit这个属性都是false为啥还要加入数据库呢?不能从数据里面分离出来吗

### ISSUE THREAD

**Issue by mgbq** [xiaoniezi/vue-tree#1]

**Comment by xiaoniezi** [comment]
因为这样直接操作比较方便。
想到另一个操作方法，不知道可不可行：
通过在`node`加这个属性，点击编辑的时候判断是否存在=》存在则改成`true`，否则就创建`this.node.isEdit = true`

**Comment by mgbq** [comment]
this.node.isEdit这个属性在哪设置？

**Comment by xiaoniezi** [comment]
在首次点击编辑的时候设置

**Comment by mgbq** [comment]
问题是this.node没有这个isEdit这个属性

**Comment by xiaoniezi** [comment]
参考了朋友的代码，在加载Tree的时候同时新增这个属性
`renderContent`的函数返回前
`this.$set(node, 'isEdit', false)`

**Comment by mgbq** [comment]
感谢你的回答，刚才我试了 
 在加载Tree的时候同时新增这个属性
renderContent的函数返回前
this.$set(node, 'isEdit', false)  可以实现,早这样设计多好

**Comment by xiaoniezi** [comment]
ok

**Comment by mgbq** [comment]
nodeEditPass(s, d, n) { // 编辑完成  你这个函数写在共用的组件里面的话，多个页面共用这个组件不是很痛苦么

**Comment by xiaoniezi** [comment]
你有更好的办法吗？
