### ISSUE TITLE
调用接口后页面是空白的

### ISSUE THREAD

**Issue by fengshifei0508** [xiaoniezi/vue-tree#10]
created () {
      this.getPersonnel()
    },
    methods: {
      getPersonnel () {
          this.$http({
            method: 'GET',
            url: '/api/operator/department/tree',
            headers: {
              'X-Access-Token': 'cloudminds_admin'
            }
          }).then((res) => {
            let result = res.data
            if (result.code === 0) {
              let arr = []
              this.maxexpandId = result.maxexpandIds
              this.non_maxexpandId = result.maxexpandIds
              arr.push(result.data.children)
              this.setTree = arr
            }
          })
      },

**Comment by xiaoniezi** [comment]
建议获取数据成功后再加载tree
BTW，根据深入响应式，可以适当优化一下代码
`this.$set(this, 'setTree', arr)`

**Comment by fengshifei0508** [comment]
d.children.push({
				id: ++this.maxexpandId,
				name: '新增节点',
				pid: d.id,
				children: []
			})
我调用后台后，新增子节点一直会出现，在父节点后也新增了，是不是这块的这个 maxexpandId 没传对引起的

**Comment by fengshifei0508** [comment]
就是我在2级子节点添加3级子节点后，1级节点也会同步添加2级节点，什么原因啊

**Comment by xiaoniezi** [comment]
能贴一下新增时的核心代码吗？

**Comment by fengshifei0508** [comment]
NodeAdd(n, d){//新增节点
        this.id = d.id
        //判断层级
        if(n.level >= 3){
          this.$message.error("最多只支持三级！")
          return false;
        }
        this.$http({
          method: 'POST',
          url: '/api/operator/department/add',
          data: {
            id: ++this.maxexpandId,
            departmentName: '新增子节点',
            parentId: this.id
          },
          headers: {
            'X-Access-Token': 'cloudminds_admin'
          }
        }).then((res) => {
          //同时展开节点
          if(!n.expanded){
            n.expanded = true
          }
          this.$message.success("成功")
          this.getPersonnel()
        })
      }

**Comment by fengshifei0508** [comment]
感觉是 this.maxexpandId 这个导致的，这个后台没有返回，我让他随便加了这值

**Comment by xiaoniezi** [comment]
我有空优化一下代码，有些地方设计是不合逻辑

**Comment by xiaoniezi** [comment]
已更新
