### ISSUE TITLE
加入show-checkbox  复选框

### ISSUE THREAD

**Issue by clisstop** [xiaoniezi/vue-tree#11]
https://xiaoniezi.github.io/2017-10-16/vue-ElementUI-tree-expand/tree加入show-checkbox  复选框后,id不是95++了 而是0--了  添加一个是-1  正常是96

**Comment by xiaoniezi** [comment]
不是很懂，贴下代码？

**Comment by clisstop** [comment]
不能发图啊  我发你网站了 https://xiaoniezi.github.io/2017-10-16/vue-ElementUI-tree-expand/  你的这个可以贴图  是不是审核后回复可见 还是我这没发过去

**Comment by xiaoniezi** [comment]
没发成功，直接复制代码贴上来
