### ISSUE TITLE
你看看这个id

### ISSUE THREAD

**Issue by clisstop** [xiaoniezi/vue-tree#12]
slotTree.vue这个文件 代码不动 给el-tree这标签加个这个属性  show-checkbox

**Comment by clisstop** [comment]
然后对比console中 childNodes(arr2)中Node[1]->data.id        未加show-checkbox  这个id是96 加了之后这个id是-1

**Comment by xiaoniezi** [comment]
我有空看下，你不要关这个issue

**Comment by clisstop** [comment]
不会玩这个东西

**Comment by clisstop** [comment]
好了好了 我知道了 我没设置NODE_ID_START

**Comment by xiaoniezi** [comment]
(⊙o⊙)…那我先close了

**Comment by clisstop** [comment]
=-=!!  俺的错 俺的错
