### ISSUE TITLE
slotTree.vue和slot_tree.vue有什么区别

### ISSUE THREAD

**Issue by zhujinhu21** [xiaoniezi/vue-tree#13]
一个用点是maxexpandId，另一个是NODE_ID_START ？

**Comment by xiaoniezi** [comment]
`slotTree.vue`是优化版本，可看更新说明[2019/04/17](https://github.com/xiaoniezi/vue-tree#20190417)

**Comment by zhujinhu21** [comment]
NODE_KEY: 'id',// id对应字段 好像只能是数字类型，后台返回的接口id是一个字符串

**Comment by xiaoniezi** [comment]
对的，因为要用来判断当前id是否新增，你可以把判断那部分去掉，自定义一个字段判断是否新增。
