### ISSUE TITLE
你好，之前用了你的组件很不错，现在有个新需求，我用了几种方法试了都不行，

### ISSUE THREAD

**Issue by jcbound** [xiaoniezi/vue-tree#16]
就是根节点是不展示 编辑和删除按钮的，其他的子节点都正常显示，我通过判断它的层级来隐藏，但是只有选中后才能获取到他的node节点来处理，而且效果也不太好，想问下您有没有什么好的思路或建议？谢谢！

**Comment by xiaoniezi** [comment]
嘿~根节点指的是第一层吗？我想到可以用`node.level`来切换class，比如：
`<span :class="[node.level === 1 ? 'node-first' : '', 'comp-tr-node--btns']"></span>`
对应按钮加个class
`.comp-tr-node--btns{
    &.node-first{
        .btn-edit,.btn-delete{ display: none; }
    }
}`

**Comment by jcbound** [comment]
感谢提出思路，解决了问题，不过切换class是在它们的父级div中的，span和button是平级关系直接用上述代码是有问题的，换到父级就好了，(๑•̀ㅂ•́)و✧

**Comment by xiaoniezi** [comment]
ok
