### ISSUE TITLE
大佬 求帮助 请求接口这里怎么做

### ISSUE THREAD

**Issue by andyzZZ2** [xiaoniezi/vue-tree#17]
大佬我拿到你这个组件了，可以用，现在我请求接口这块要怎么写的呀？ 我请求到了后台的数据，然后怎么把数据渲染过来

//这是 api/js里面的
axios.post('接口').then(res=>{
	//这要怎么写呀？
}).catch(error=>{
	console.log(error)
})
小白 不懂的地方太多了，

**Comment by andyzZZ2** [comment]
看到错误的地方了，，，

**Comment by xiaoniezi** [comment]
解决了？

**Comment by andyzZZ2** [comment]
我前面接收用的字符串接收，应该用数组接收的，一直没看到，刚刚看到了，感谢感谢！！！

**Comment by xiaoniezi** [comment]
ok
