### ISSUE TITLE
您好，很棒的项目~！请教您一个问题

### ISSUE THREAD

**Issue by ChildhoodSummer** [xiaoniezi/vue-tree#18]
我现在有一个需求，需求的大部分功能您都实现了。大概是做一个类似vscode左侧的文件树，不同的是新增节点的时候在当前节点的子节点新增一个输入框，输入框的位置要始终显示在当前树的可视界面上。输入框失焦后，输入框消失，取而代之的是刚刚新建的节点。需求大概是这些。我在做的时候在新建输入框的定位思路上没有头绪。我不是伸手党，您给点思路就行哈~

**Comment by xiaoniezi** [comment]
hei~新增节点的时候手动push一个children，然后立即将该子节点进入编辑状态，这样就能出现输入框

**Comment by ChildhoodSummer** [comment]
十分感谢
