### ISSUE TITLE
bug 方法调用二次

### ISSUE THREAD

**Issue by mgbq** [xiaoniezi/vue-tree#4]
当我要编辑回车的时候
@blur.stop="nodeEditPass(STORE,DATA,NODE)" @keyup.enter.stop.native="nodeEditPass(STORE,DATA,NODE)"
这个二个方法都执行了
麻烦你百忙中解答下

**Comment by mgbq** [comment]
事实上我只需要调用一次

**Comment by mgbq** [comment]
已经解决了

**Comment by xiaoniezi** [comment]
厉害了，咋解决的？

**Comment by mgbq** [comment]
其实非常简单，换个思路，既然@blur事件不管怎么样都会执行，那么@keyup.enter只需要   // 编辑完成  n.isEdit = false 把编辑输入框隐藏，一行代码即可。
