### ISSUE TITLE
把你的页面直接复制到自己的里面 是空的 不显示内容

### ISSUE THREAD

**Issue by shen-lan** [xiaoniezi/vue-tree#5]
也不会报错 大概是什么原因·

**Comment by xiaoniezi** [comment]
看一下dom里面有没有加载到

**Comment by shen-lan** [comment]
> 看一下dom里面有没有加载到
DOM里  没有任何东西。只有类似template出现的注释虚线-----
采用的是render方式。
实在不行我再检查下  。可能是我那里漏了

**Comment by shen-lan** [comment]
多谢热心解答

**Comment by xiaoniezi** [comment]
是不是用了路由，但是没有跳转

**Comment by shen-lan** [comment]
跟路由没关....
sorry  是我sb了
        deactivated() {
            this.initExpand();
        },
看错了。事件不小心放在了页面解除激活事件里...
