### ISSUE TITLE
删除了节点Tree Node没有更新

### ISSUE THREAD

**Issue by developbiao** [xiaoniezi/vue-tree#6]
你好，使用demo代码slot_tree.vue，操作删除了省下面的市节点,Tree dom没有更新，数据this.setTree打印确实已经移除了。 请问一下是什么原因，谢谢~

**Comment by developbiao** [comment]
想了一个临时解决方案，在DelFun方法里面加了一行，删除成功后重新给“this.setTree” 重新copy赋值就好了。
```javascript
this.setTree = this.copyData(this.setTree)
// copy data
 copyData(data){
            let obj = {}
            obj = JSON.parse(JSON.stringify(data))
            return obj
        }
```

**Comment by xiaoniezi** [comment]
> 想了一个临时解决方案，在DelFun方法里面加了一行，删除成功后重新给“this.setTree” 重新copy赋值就好了。
> 
> ```js
> this.setTree = this.copyData(this.setTree)
> // copy data
>  copyData(data){
>             let obj = {}
>             obj = JSON.parse(JSON.stringify(data))
>             return obj
>         }
> ```

six six six
