### ISSUE TITLE
点编辑按钮没有反应

### ISSUE THREAD

**Issue by liuqiangh** [xiaoniezi/vue-tree#8]
在vue里自己造的假数据是可以正常编辑和删除的，但是调用了后端数据之后，可以正常显示，也可以删除，但就是点编辑的时候不出现输入框，看了一下idEdit已经变成了true，请问一下这是为什么呢？

**Comment by xiaoniezi** [comment]
是参数写错了吗？是isEdit吗？看下input绑定的参数是否与你设置的关键字对应

**Comment by liuqiangh** [comment]
对的，是isEdit，点编辑之后不出现对话框，nodeEditPass这个函数也不执行，然后post了一下，发现post给后端的数据中isEdit变成了true，不造咋回事

**Comment by xiaoniezi** [comment]
可以贴一下代码吗？

**Comment by liuqiangh** [comment]
整个工程代码有点儿多就不都贴了，就是在主程序中的methods里加了获取后端数据的方法，这里应该是没有问题的吧，因为可以正常显示，目前只有三条数据
![1](https://user-images.githubusercontent.com/29683167/49644171-b40fd980-fa52-11e8-882c-d9685aef1237.PNG)
![default](https://user-images.githubusercontent.com/29683167/49644187-bc681480-fa52-11e8-8510-32a7be51d001.PNG)
获取到后给文件夹加了id，给每个数据加了isEdit属性，其他几乎没有改动，这是tree_render文件
![2](https://user-images.githubusercontent.com/29683167/49644348-1d8fe800-fa53-11e8-8520-d395bfc41c92.PNG)

**Comment by xiaoniezi** [comment]
原因暂时不知，不确定是不是isEdit设置有误，建议换用slot的方法，可以[参考文件](https://github.com/xiaoniezi/tree/blob/master/src/view/slot_tree.vue)，这样就不用自己设置isEdit

**Comment by liuqiangh** [comment]
好的，谢谢您的回复~我试一下~
