### ISSUE TITLE
为什么删除之后，显示成功但是dom没有消失？

### ISSUE THREAD

**Issue by knife0217** [xiaoniezi/vue-tree#9]

**Comment by xiaoniezi** [comment]
hi，你用的是slot模式吗？可以贴一下主要代码吗？

**Comment by knife0217** [comment]
是slot模式，函数没有改，只是放在我的页面中就不管用了，确实是删除了，只是切换页面后才可以看到，函数执行完显示删除成功后没有消失，
还有这个怎么贴图片 :)

**Comment by knife0217** [comment]
我在二次确认中 调DelFun（）时加了￥next Tick（）也不管用啊
.then(() => {
            this.$nextTick(() => {
              DelFun()
            })
})

**Comment by xiaoniezi** [comment]
> 我在二次确认中 调DelFun（）时加了￥next Tick（）也不管用啊
> .then(() => {
> this.$nextTick(() => {
> DelFun()
> })
> })

方便贴一下删除事件`NodeDel`的代码吗？是否遗漏or删除了某些字段？

**Comment by knife0217** [comment]
NodeDel(n, d) { // 删除节点
      console.log(n, d)
      const that = this
      if (d.children && d.children.length !== 0) {
        this.$message.error('此节点有子级，不可删除！')
        return false
      } else {
        // 新增节点可直接删除，已存在的节点要二次确认
        // 删除操作
        const DelFun = () => {
          const _list = n.parent.data.children || n.parent.data// 节点同级数据
          const _index = _list.map((c) => c.id).indexOf(d.id)
          console.log(_index)
          _list.splice(_index, 1)
          this.$message.success('删除成功！')
        }
        // 二次确认
        const ConfirmFun = () => {
          this.$confirm('是否删除此节点？', '提示', {
            confirmButtonText: '确认',
            cancelButtonText: '取消',
            type: 'warning'
          }).then(() => {
            this.$nextTick(() => {
              DelFun()
            })
          }).catch(() => {})
        }
        // 判断是否是新增节点
        d.id > this.non_maxexpandId ? DelFun() : ConfirmFun()
      }
    },

**Comment by knife0217** [comment]
clone你的项目独自运行，删除功能没有问题，我把代码贴过来后碰到了这个问题，感觉很蒙B。先谢谢大佬了，麻烦了

**Comment by knife0217** [comment]
![_20190107150319](https://user-images.githubusercontent.com/40013098/50754398-a1c2ce80-1290-11e9-8ac6-de1ebdb26bf1.png)
![_20190107152659](https://user-images.githubusercontent.com/40013098/50754424-b4d59e80-1290-11e9-8d94-af0dacd571a0.png)

**Comment by xiaoniezi** [comment]
emmm那问题来了，你的接口请求到的城市键值key是`id`吗？

**Comment by knife0217** [comment]
还没有调接口，先用的你写好的数据
![_20190107153408](https://user-images.githubusercontent.com/40013098/50754749-b2c00f80-1291-11e9-9159-ec3ef37988c0.png)

**Comment by xiaoniezi** [comment]
其他功能是否有问题？
```
let DelFun = () => {
	let _list = n.parent.data.children || n.parent.data;//节点同级数据
	let _index = _list.map((c) => c.id).indexOf(d.id);
	console.log(_list, _index)
	_list.splice(_index, 1);
	this.$message.success("删除成功！")
}
```
打印出来的`_list, _index`有问题吗？

**Comment by knife0217** [comment]
![_20190107160029](https://user-images.githubusercontent.com/40013098/50755882-637bde00-1295-11e9-8077-63219aef5ce7.png)

**Comment by knife0217** [comment]
_list.splice(_index, 1)方法好像在console.log(_list, _index)之前就执行了

**Comment by xiaoniezi** [comment]
因为你的数据更新了，所以打印出来才少了一项。
你用的饿了么版本是多少？现在是数据更新了，dom没有更新
删除之后打印tree看看data有没有更新？

**Comment by xiaoniezi** [comment]
我真是太蠢了……ElementUI已经提供了删除的api
[看这里](http://element-cn.eleme.io/#/zh-CN/component/tree#fang-fa)的`remove`
```
const DelFun = () => {
	this.nextTick(() => {
		if(this.$refs.SlotMenuList){
			this.$refs.SlotMenuList.remove(n)
			this.$message.success("删除成功！")
		}
	})
}
```

**Comment by knife0217** [comment]
我在watch console的setTree 显示是删除后的数据，dom就是不更新。。

![Uploading 微信图片_20190107163029.png…]()

**Comment by knife0217** [comment]
![_20190107165800](https://user-images.githubusercontent.com/40013098/50758529-6b3f8080-129d-11e9-8ffa-c46db73943ca.png)
还有大佬能讲讲这样写的原理吗，给大佬跪了

**Comment by xiaoniezi** [comment]
> ![_20190107165800](https://user-images.githubusercontent.com/40013098/50758529-6b3f8080-129d-11e9-8ffa-c46db73943ca.png)
> 还有大佬能讲讲这样写的原理吗，给大佬跪了

尴尬了￣□￣｜｜我是加了啊……

**Comment by gloriachenjing** [comment]
> 是slot模式，函数没有改，只是放在我的页面中就不管用了，确实是删除了，只是切换页面后才可以看到，函数执行完显示删除成功后没有消失，
> 还有这个怎么贴图片 :)
你好 slot方法你是怎么加到你的页面的？作为组件导入进去的吗？我作为组件导入到我的页面slot里面的e东西都没方法用 只能显示tree不能曾删改 但是我用render的那个导入我的页面就可以 是使用slot需要再配置什么吗？新手不懂 望指教

**Comment by xiaoniezi** [comment]
> > 是slot模式，函数没有改，只是放在我的页面中就不管用了，确实是删除了，只是切换页面后才可以看到，函数执行完显示删除成功后没有消失，
> > 还有这个怎么贴图片 :)
> > 你好 slot方法你是怎么加到你的页面的？作为组件导入进去的吗？我作为组件导入到我的页面slot里面的e东西都没方法用 只能显示tree不能曾删改 但是我用render的那个导入我的页面就可以 是使用slot需要再配置什么吗？新手不懂 望指教

最新版的element-ui有自带的增删改api，建议使用官方的文档
